# Generated by Django 5.2.17 on 2026-09-14 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'filial',
                'verbose_name_plural': 'filiais',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nome')),
                ('tracking', models.CharField(choices=[('quantity', 'Quantidade'), ('individual', 'Patrimônio individual')], max_length=15, verbose_name='controle')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'tipo de item',
                'verbose_name_plural': 'tipos de item',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=80, unique=True, verbose_name='patrimônio')),
                ('serial', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='número de série')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.branch', verbose_name='filial atual')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='inventory.item', verbose_name='tipo de item')),
            ],
            options={
                'verbose_name': 'equipamento',
                'verbose_name_plural': 'equipamentos',
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantidade')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.branch', verbose_name='filial')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.item', verbose_name='item')),
            ],
            options={
                'verbose_name': 'saldo',
                'verbose_name_plural': 'saldos',
                'constraints': [models.UniqueConstraint(fields=('branch', 'item'), name='unique_branch_item'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='nonnegative_balance')],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Saída'), ('transfer', 'Transferência')], max_length=10, verbose_name='movimentação')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('reason', models.CharField(max_length=300, verbose_name='motivo / chamado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.asset', verbose_name='equipamento')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming', to='inventory.branch', verbose_name='destino')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.item', verbose_name='item')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing', to='inventory.branch', verbose_name='origem')),
            ],
            options={
                'verbose_name': 'movimentação',
                'verbose_name_plural': 'movimentações',
                'ordering': ['-created_at', '-pk'],
                'default_permissions': ('add', 'view'),
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='positive_movement_quantity')],
            },
        ),
    ]
