# Generated by Django 5.2.17 on 2026-09-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('unknown', 'Não informado'), ('working', 'Funcionando'), ('testing', 'A testar'), ('defective', 'Com defeito'), ('incomplete', 'Incompleto / sem acessório'), ('mixed', 'Condições variadas (ver observações)')], default='unknown', max_length=15, verbose_name='condição'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=120, verbose_name='localização interna'),
        ),
        migrations.AddField(
            model_name='asset',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, verbose_name='observações'),
        ),
        migrations.AddField(
            model_name='balance',
            name='condition',
            field=models.CharField(choices=[('unknown', 'Não informado'), ('working', 'Funcionando'), ('testing', 'A testar'), ('defective', 'Com defeito'), ('incomplete', 'Incompleto / sem acessório'), ('mixed', 'Condições variadas (ver observações)')], default='unknown', max_length=15, verbose_name='condição'),
        ),
        migrations.AddField(
            model_name='balance',
            name='location',
            field=models.CharField(blank=True, max_length=120, verbose_name='localização interna'),
        ),
        migrations.AddField(
            model_name='balance',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, verbose_name='observações'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, verbose_name='observações do tipo de item'),
        ),
        migrations.AddField(
            model_name='movement',
            name='recipient',
            field=models.CharField(blank=True, max_length=150, verbose_name='colaborador destinatário'),
        ),
        migrations.AddField(
            model_name='movement',
            name='recipient_department',
            field=models.CharField(blank=True, max_length=100, verbose_name='setor do destinatário'),
        ),
    ]
