# Generated by Django 5.2.17 on 2026-09-16 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_asset_condition_asset_location_asset_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tag',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='patrimônio'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('\\A[0-9]+\\Z', 'Informe somente números de 0 a 9 no código da filial.')], verbose_name='código'),
        ),
    ]
